### ISSUE TITLE
Changes are not taken into consideration.

### ISSUE THREAD

**Issue by mysther78** [DetroitApps/RetroMultiManager#1]
Hello,

I'm new to AKH language, I'm trying to modify scenario code but my modifications aren't take into considerations, could you help me ?

I've already clone it and create new local branch, modifications are correctly saved in Scenarios/ folder...

Btw I'm very interested in your project.

**Comment by mysther78** [comment]
Ok, found it, I needed to start Tool/Realease Maker.ahk

**Comment by DetroitApps** [comment]
Hello,

Thank you for your interest in this project! Do note that custom scenarios are far from being fully implemented, but I'm glad you decided to try it out already.

You guessed it, scenarios need to be merged in a single file to work, but you can directly use the tool Scenario Merger that only does this compilation. 

**Scenario Merger**: merge all files from Scenarios in Scenarios/Out/MergedScenarios.ahk
**Release Maker**: tool to create archives for GitHub releases. It indeed makes a call to Scenario Merger to make sure it includes the latest merged scenarios.

An even better way to do it would be to activate Dev mode through the _settings.ini_ file. All scenarios will be merged at launch (given the latest modifications of the merged scenario file is 10 seconds ago or more). Dev mode will also skip the master password prompt, defaulting to "dev" as a password.

I apologize for not writing any docs about that part of the project yet, so do not hesitate to ask any questions if needed.
