### ISSUE TITLE
Remap the switch keys

### ISSUE THREAD

**Issue by GaldanM** [DetroitApps/RetroMultiManager#12]
Hi,

Since I began playing, I've always used the key "F1" to pass, is it possible to customize the hotkeys to switch to other instances ?

Love your tool, thanks !

**Comment by mysther78** [comment]
Hello,

Unfortunately, it's not customizable directly from the application, however as the source code is free, you can modify it directly from the source code!

Do you know how to do it, do you need help compiling the source code?

The instructions you need to change are in the file /src/class/settings.ahk line 140

**Comment by GaldanM** [comment]
Well, I'm a developer myself but it's the first time with AutoHotkey ahah, I'll search some documentation.

Thanks for taking the time to check the line, it will save me some time !
