### ISSUE TITLE
resolution 1600x900

### ISSUE THREAD

**Issue by Renarza** [DetroitApps/RetroMultiManager#13]
Hello i have a problem with the following resolution 1600x900 preventing me from using it cordially.

**Comment by mysther78** [comment]
Hello, what is the issue exactly ?

I updated github's readme to allow people to add their own resolution in RMM 😄 ([see here](https://github.com/DetroitApps/RetroMultiManager#limitations))

**Comment by mysther78** [comment]
Resolution added 🙂
