### ISSUE TITLE
Strange program behavior

### ISSUE THREAD

**Issue by vapaternina** [DetroitApps/RetroMultiManager#14]
I am trying to log in with 8 Dofus Ascalion accounts but the first two appear without the label of the character class that I use in that account in the Windows taskbar button and the pointer begins to move by itself and it seems that it is doing the same selecting the username and password fields but never maximizing the windows. Then he maxes from account 3 to 8 and logs them in. If I don't click on "Link" before everything starts it says that there is an error with the .INI when it is going to select the server...
Resolution: 1920x1080
My setup:

![image](https://user-images.githubusercontent.com/16907375/104250311-57562880-543b-11eb-9764-37b9574bb621.png)
![image](https://user-images.githubusercontent.com/16907375/104250497-b9af2900-543b-11eb-80ca-41021be58f12.png)
I leave this image where it is seen that he opened 8 clients but I only take into six accounts.
![image](https://user-images.githubusercontent.com/16907375/104250267-3a215a00-543b-11eb-8cd1-866bd8636cd1.png)
When I try with 4 accounts only works 2...
This appears always if I dont force the link with de Link Button:
![image](https://user-images.githubusercontent.com/16907375/104265716-3520d280-545c-11eb-9c0a-9797a017214f.png)

**Comment by vapaternina** [comment]
I add: now I try to use 4 and it only takes 2.

**Comment by mysther78** [comment]
Hello,
Which version of RMM are you running ? Your issue look Ike an old one. ^^
Regards,

**Comment by vapaternina** [comment]
Lastest, 1.2.1

**Comment by mysther78** [comment]
Ok after investigation, this issue is due to the missing "initiative" information.

I will close this issue when I will release a fix ;)

**Comment by vapaternina** [comment]
Thanks a lot. It works when I place the initiative.
