### ISSUE TITLE
Use of 'ahk PID' of dofus is a bad idea ?

### ISSUE THREAD

**Issue by mysther78** [DetroitApps/RetroMultiManager#2]
Hello,

RMM works well with one account, but not with two accounts because of the PID Dofus.

When you launch a Dofus window, Windows runs several processes "Dofus.exe" (so with several PIDs). It seems that PIDs appear and disappear after the second account is opened.

Have you ever had this problem?

See picture bellow :
![image](https://user-images.githubusercontent.com/50944755/68996743-822c0780-089e-11ea-9fb1-3fbc81445bb4.png)

![image](https://user-images.githubusercontent.com/50944755/68996771-e058ea80-089e-11ea-9fa7-b5b62d85c431.png)

**Comment by mysther78** [comment]
![image](https://user-images.githubusercontent.com/50944755/68998635-4e101100-08b5-11ea-8482-974ab582598e.png)


![image](https://user-images.githubusercontent.com/50944755/68998622-320c6f80-08b5-11ea-9ce9-ae9f54b22eff.png)


More informations here

**Comment by DetroitApps** [comment]
Hello,

Are you using the 32 or 64 bits version of Dofus ?

The 32 bits version is the preferred one and can be found in %AppData%\..\Local\Ankama\zaap\retro\resources\app.asar.unpacked\retroclient.

Let me know if it changes something.

**Comment by mysther78** [comment]
I rewrote part of the code, it seems to work better now.

I look at how to push my git branch on your repository, I can join you on discord to facilitate future discussions?

**Comment by DetroitApps** [comment]
I created a Discord for Retro Multi Manager, it is available here: https://discordapp.com/invite/5me7w4u.

Otherwise my Discord is Detroit#1023.
