### ISSUE TITLE
Ne fonctionne plus depuis dernière MAJ Dofus

### ISSUE THREAD

**Issue by gpirick** [DetroitApps/RetroMultiManager#5]
Bonjour ! merci tout dabord pour ton logiciel il est très pratique et façile d'utilisation, mlaheureusement la dernière MAJ dofus 1.30.9 à casser le script de lancement des fenêtres et le programme n'est donc plus utilisable pour le moment.

**Comment by DetroitApps** [comment]
Bonjour,

Effectivement on me l'a signalé assez rapidement. Je suis en train de voir pour un fix.

Merci pour ton message.

**Comment by kriss13** [comment]
Bonjour , 
Tous d'abord  merci pour ton coup de  pouce au  multi compte ;) 

aurais tu une date ou un timing  a  nous transmettre pour la remise en route du Logiciel ?  

sinon bon boulot  ;)

**Comment by DetroitApps** [comment]
Salut kriss13,

Le soft sera de nouveau fonctionnel ce soir. 

J'ai déjà réglé le problème, j'incorpore les derniers bugfixes que je n'avais pas encore envoyé et je poste une nouvelle version.

**Comment by kriss13** [comment]
merci beaucoup sa fait plaisir  =)  très bonne réactivité de votre part

**Comment by gpirick** [comment]
Voila tout fonctionne parfaitement, je te remercie infiniment super boulot !

**Comment by gpirick** [comment]
Est-il possible de changer la touche pour le scénario CycleWindows ? j'ai chercher dans le script et modifier CapsLock par Numlock 3 mais ça ne fonctionne pas

**Comment by DetroitApps** [comment]
J'ai prévu de rajouter un menu pour modifier les raccourcis dans une future mise à jour.

En attendant tu peux effectivement modifier le scénario CycleWindows. Il faut néanmoins que tu exécutes le fichier Tools/ScenarioMerger.ahk après toutes modifications de scénarios pour qu'elles soient prises en compte.

Le raccourci est toujours Win+² mais c'est un oubli de ma part, je vais le changer de suite pour Win+CapsLock.

**Comment by gpirick** [comment]
Merci de ta réponse, dans quel fichier dois-je me rendre pour modifier le raccourci win+² ? il ne semble pas fonctionner chez moi.

**Comment by DetroitApps** [comment]
Je t'invite à passer sur le Discord directement, ce sera plus simple pour t'aider! (http://discord.gg/5me7w4u)
