### ISSUE TITLE
Incompatible avec le launcher 32 BIT

### ISSUE THREAD

**Issue by papguac** [DetroitApps/RetroMultiManager#7]
Lorsque je set le PATH sur l'application 32 bit j'ai un retour d'une fenetre prompt avec le message d'erreur : windows ne trouve pas './resources/app.asak.unpacked/retroclient/dofus.exe. 
Pourtant en utilisant le client normal tout va bien ou bien meme en lancant l'app 32 bit.

**Comment by mysther78** [comment]
Bonjour,

Il existe deux applications Dofus 32bits dans le répertoire : 
- "Dofus_32bits.exe" dans le répertoire racine de Dofus Rétro,
- "Dofus.exe" dans le répertoire "retro\resources\app.asar.unpacked\retroclient"

Cependant c'est avec le deuxième qu'il faut ouvrir exécutable avec notre application !
Peux-tu me confirmer l'application avec laquelle tu lances le jeu ?

**Comment by papguac** [comment]
C'était effectivement le premier que j'utilisais, aussi facile que sa, un gigantesque merci!
